#!/bin/bash
echo "Stopping app..."
#kill `ps -ef | grep 'virtualenv/bin/imgr' | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
kill `ps -ef | grep 'virtualenv/bin/celery' | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
exit 0
